name: HeadPet
version: ${project.version}
main: sp.yeyu.headpetfeature.headpet.HeadPet
commands:
  pet:
    description: <Dev Mode> give sample head of the requested feature
    usage: /pet [function name] like /pet fortune box